// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExceptionDetails.proto

package by.lamaka.resume.dto;

public final class ExceptionDetailsOuterClass {
  private ExceptionDetailsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExceptionDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExceptionDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ExceptionDetails.proto\"4\n\020ExceptionDet" +
      "ails\022\017\n\007message\030\001 \001(\t\022\017\n\007details\030\002 \001(\tB\030" +
      "\n\024by.lamaka.resume.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ExceptionDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExceptionDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExceptionDetails_descriptor,
        new java.lang.String[] { "Message", "Details", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
