// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExceptionDetails.proto

package by.lamaka.resume.dto;

public interface ExceptionDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExceptionDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string details = 2;</code>
   * @return The details.
   */
  java.lang.String getDetails();
  /**
   * <code>string details = 2;</code>
   * @return The bytes for details.
   */
  com.google.protobuf.ByteString
      getDetailsBytes();
}
