// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResumeDTO.proto

package by.lamaka.resume.dto;

public interface ListResumeDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListResumeDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  java.util.List<by.lamaka.resume.dto.ResumeDTO> 
      getResumeDTOList();
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  by.lamaka.resume.dto.ResumeDTO getResumeDTO(int index);
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  int getResumeDTOCount();
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  java.util.List<? extends by.lamaka.resume.dto.ResumeDTOOrBuilder> 
      getResumeDTOOrBuilderList();
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  by.lamaka.resume.dto.ResumeDTOOrBuilder getResumeDTOOrBuilder(
      int index);
}
