// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResumeDTO.proto

package by.lamaka.resume.dto;

/**
 * Protobuf type {@code ListResumeDTO}
 */
public final class ListResumeDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListResumeDTO)
    ListResumeDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListResumeDTO.newBuilder() to construct.
  private ListResumeDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListResumeDTO() {
    resumeDTO_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListResumeDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListResumeDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              resumeDTO_ = new java.util.ArrayList<by.lamaka.resume.dto.ResumeDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            resumeDTO_.add(
                input.readMessage(by.lamaka.resume.dto.ResumeDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        resumeDTO_ = java.util.Collections.unmodifiableList(resumeDTO_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return by.lamaka.resume.dto.ResumeDTOOuterClass.internal_static_ListResumeDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return by.lamaka.resume.dto.ResumeDTOOuterClass.internal_static_ListResumeDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            by.lamaka.resume.dto.ListResumeDTO.class, by.lamaka.resume.dto.ListResumeDTO.Builder.class);
  }

  public static final int RESUMEDTO_FIELD_NUMBER = 1;
  private java.util.List<by.lamaka.resume.dto.ResumeDTO> resumeDTO_;
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  @java.lang.Override
  public java.util.List<by.lamaka.resume.dto.ResumeDTO> getResumeDTOList() {
    return resumeDTO_;
  }
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends by.lamaka.resume.dto.ResumeDTOOrBuilder> 
      getResumeDTOOrBuilderList() {
    return resumeDTO_;
  }
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  @java.lang.Override
  public int getResumeDTOCount() {
    return resumeDTO_.size();
  }
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  @java.lang.Override
  public by.lamaka.resume.dto.ResumeDTO getResumeDTO(int index) {
    return resumeDTO_.get(index);
  }
  /**
   * <code>repeated .ResumeDTO resumeDTO = 1;</code>
   */
  @java.lang.Override
  public by.lamaka.resume.dto.ResumeDTOOrBuilder getResumeDTOOrBuilder(
      int index) {
    return resumeDTO_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resumeDTO_.size(); i++) {
      output.writeMessage(1, resumeDTO_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < resumeDTO_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, resumeDTO_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof by.lamaka.resume.dto.ListResumeDTO)) {
      return super.equals(obj);
    }
    by.lamaka.resume.dto.ListResumeDTO other = (by.lamaka.resume.dto.ListResumeDTO) obj;

    if (!getResumeDTOList()
        .equals(other.getResumeDTOList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResumeDTOCount() > 0) {
      hash = (37 * hash) + RESUMEDTO_FIELD_NUMBER;
      hash = (53 * hash) + getResumeDTOList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static by.lamaka.resume.dto.ListResumeDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(by.lamaka.resume.dto.ListResumeDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListResumeDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListResumeDTO)
      by.lamaka.resume.dto.ListResumeDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return by.lamaka.resume.dto.ResumeDTOOuterClass.internal_static_ListResumeDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return by.lamaka.resume.dto.ResumeDTOOuterClass.internal_static_ListResumeDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              by.lamaka.resume.dto.ListResumeDTO.class, by.lamaka.resume.dto.ListResumeDTO.Builder.class);
    }

    // Construct using by.lamaka.resume.dto.ListResumeDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResumeDTOFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resumeDTOBuilder_ == null) {
        resumeDTO_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resumeDTOBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return by.lamaka.resume.dto.ResumeDTOOuterClass.internal_static_ListResumeDTO_descriptor;
    }

    @java.lang.Override
    public by.lamaka.resume.dto.ListResumeDTO getDefaultInstanceForType() {
      return by.lamaka.resume.dto.ListResumeDTO.getDefaultInstance();
    }

    @java.lang.Override
    public by.lamaka.resume.dto.ListResumeDTO build() {
      by.lamaka.resume.dto.ListResumeDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public by.lamaka.resume.dto.ListResumeDTO buildPartial() {
      by.lamaka.resume.dto.ListResumeDTO result = new by.lamaka.resume.dto.ListResumeDTO(this);
      int from_bitField0_ = bitField0_;
      if (resumeDTOBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          resumeDTO_ = java.util.Collections.unmodifiableList(resumeDTO_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.resumeDTO_ = resumeDTO_;
      } else {
        result.resumeDTO_ = resumeDTOBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof by.lamaka.resume.dto.ListResumeDTO) {
        return mergeFrom((by.lamaka.resume.dto.ListResumeDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(by.lamaka.resume.dto.ListResumeDTO other) {
      if (other == by.lamaka.resume.dto.ListResumeDTO.getDefaultInstance()) return this;
      if (resumeDTOBuilder_ == null) {
        if (!other.resumeDTO_.isEmpty()) {
          if (resumeDTO_.isEmpty()) {
            resumeDTO_ = other.resumeDTO_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResumeDTOIsMutable();
            resumeDTO_.addAll(other.resumeDTO_);
          }
          onChanged();
        }
      } else {
        if (!other.resumeDTO_.isEmpty()) {
          if (resumeDTOBuilder_.isEmpty()) {
            resumeDTOBuilder_.dispose();
            resumeDTOBuilder_ = null;
            resumeDTO_ = other.resumeDTO_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resumeDTOBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResumeDTOFieldBuilder() : null;
          } else {
            resumeDTOBuilder_.addAllMessages(other.resumeDTO_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      by.lamaka.resume.dto.ListResumeDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (by.lamaka.resume.dto.ListResumeDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<by.lamaka.resume.dto.ResumeDTO> resumeDTO_ =
      java.util.Collections.emptyList();
    private void ensureResumeDTOIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        resumeDTO_ = new java.util.ArrayList<by.lamaka.resume.dto.ResumeDTO>(resumeDTO_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        by.lamaka.resume.dto.ResumeDTO, by.lamaka.resume.dto.ResumeDTO.Builder, by.lamaka.resume.dto.ResumeDTOOrBuilder> resumeDTOBuilder_;

    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public java.util.List<by.lamaka.resume.dto.ResumeDTO> getResumeDTOList() {
      if (resumeDTOBuilder_ == null) {
        return java.util.Collections.unmodifiableList(resumeDTO_);
      } else {
        return resumeDTOBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public int getResumeDTOCount() {
      if (resumeDTOBuilder_ == null) {
        return resumeDTO_.size();
      } else {
        return resumeDTOBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public by.lamaka.resume.dto.ResumeDTO getResumeDTO(int index) {
      if (resumeDTOBuilder_ == null) {
        return resumeDTO_.get(index);
      } else {
        return resumeDTOBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder setResumeDTO(
        int index, by.lamaka.resume.dto.ResumeDTO value) {
      if (resumeDTOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResumeDTOIsMutable();
        resumeDTO_.set(index, value);
        onChanged();
      } else {
        resumeDTOBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder setResumeDTO(
        int index, by.lamaka.resume.dto.ResumeDTO.Builder builderForValue) {
      if (resumeDTOBuilder_ == null) {
        ensureResumeDTOIsMutable();
        resumeDTO_.set(index, builderForValue.build());
        onChanged();
      } else {
        resumeDTOBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder addResumeDTO(by.lamaka.resume.dto.ResumeDTO value) {
      if (resumeDTOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResumeDTOIsMutable();
        resumeDTO_.add(value);
        onChanged();
      } else {
        resumeDTOBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder addResumeDTO(
        int index, by.lamaka.resume.dto.ResumeDTO value) {
      if (resumeDTOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResumeDTOIsMutable();
        resumeDTO_.add(index, value);
        onChanged();
      } else {
        resumeDTOBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder addResumeDTO(
        by.lamaka.resume.dto.ResumeDTO.Builder builderForValue) {
      if (resumeDTOBuilder_ == null) {
        ensureResumeDTOIsMutable();
        resumeDTO_.add(builderForValue.build());
        onChanged();
      } else {
        resumeDTOBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder addResumeDTO(
        int index, by.lamaka.resume.dto.ResumeDTO.Builder builderForValue) {
      if (resumeDTOBuilder_ == null) {
        ensureResumeDTOIsMutable();
        resumeDTO_.add(index, builderForValue.build());
        onChanged();
      } else {
        resumeDTOBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder addAllResumeDTO(
        java.lang.Iterable<? extends by.lamaka.resume.dto.ResumeDTO> values) {
      if (resumeDTOBuilder_ == null) {
        ensureResumeDTOIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resumeDTO_);
        onChanged();
      } else {
        resumeDTOBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder clearResumeDTO() {
      if (resumeDTOBuilder_ == null) {
        resumeDTO_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resumeDTOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public Builder removeResumeDTO(int index) {
      if (resumeDTOBuilder_ == null) {
        ensureResumeDTOIsMutable();
        resumeDTO_.remove(index);
        onChanged();
      } else {
        resumeDTOBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public by.lamaka.resume.dto.ResumeDTO.Builder getResumeDTOBuilder(
        int index) {
      return getResumeDTOFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public by.lamaka.resume.dto.ResumeDTOOrBuilder getResumeDTOOrBuilder(
        int index) {
      if (resumeDTOBuilder_ == null) {
        return resumeDTO_.get(index);  } else {
        return resumeDTOBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public java.util.List<? extends by.lamaka.resume.dto.ResumeDTOOrBuilder> 
         getResumeDTOOrBuilderList() {
      if (resumeDTOBuilder_ != null) {
        return resumeDTOBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(resumeDTO_);
      }
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public by.lamaka.resume.dto.ResumeDTO.Builder addResumeDTOBuilder() {
      return getResumeDTOFieldBuilder().addBuilder(
          by.lamaka.resume.dto.ResumeDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public by.lamaka.resume.dto.ResumeDTO.Builder addResumeDTOBuilder(
        int index) {
      return getResumeDTOFieldBuilder().addBuilder(
          index, by.lamaka.resume.dto.ResumeDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .ResumeDTO resumeDTO = 1;</code>
     */
    public java.util.List<by.lamaka.resume.dto.ResumeDTO.Builder> 
         getResumeDTOBuilderList() {
      return getResumeDTOFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        by.lamaka.resume.dto.ResumeDTO, by.lamaka.resume.dto.ResumeDTO.Builder, by.lamaka.resume.dto.ResumeDTOOrBuilder> 
        getResumeDTOFieldBuilder() {
      if (resumeDTOBuilder_ == null) {
        resumeDTOBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            by.lamaka.resume.dto.ResumeDTO, by.lamaka.resume.dto.ResumeDTO.Builder, by.lamaka.resume.dto.ResumeDTOOrBuilder>(
                resumeDTO_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        resumeDTO_ = null;
      }
      return resumeDTOBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListResumeDTO)
  }

  // @@protoc_insertion_point(class_scope:ListResumeDTO)
  private static final by.lamaka.resume.dto.ListResumeDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new by.lamaka.resume.dto.ListResumeDTO();
  }

  public static by.lamaka.resume.dto.ListResumeDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListResumeDTO>
      PARSER = new com.google.protobuf.AbstractParser<ListResumeDTO>() {
    @java.lang.Override
    public ListResumeDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListResumeDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListResumeDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListResumeDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public by.lamaka.resume.dto.ListResumeDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

