// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResumeDTO.proto

package by.lamaka.resume.dto;

public interface ResumeDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResumeDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string second_name = 3;</code>
   * @return The secondName.
   */
  java.lang.String getSecondName();
  /**
   * <code>string second_name = 3;</code>
   * @return The bytes for secondName.
   */
  com.google.protobuf.ByteString
      getSecondNameBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phone_number = 5;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 5;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
